//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raamen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTool
    {
        public int DetailToolid { get; set; }
        public int Headerid { get; set; }
        public Nullable<int> Ramenid { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual HeaderTool HeaderTool { get; set; }
        public virtual Raman Raman { get; set; }
    }
}
