//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raamen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int Id { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> Staffid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual User User { get; set; }
    }
}
